version: '3.7'
networks:
    SLIM_4_API:
volumes:
    logs:
        driver: local

services:
    nginx:
        image: nginx:stable-alpine
        container_name: slim_nginx
        volumes:
            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - SLIM_4_API
    php:
        build:
            context: ./docker/images/php/
            dockerfile: Dockerfile
            args:
                COMPOSER: 1
                XDEBUG: 1
        container_name: slim_php

        working_dir: /var/www
        environment:
            PHP_IDE_CONFIG: serverName=distance_calculator
            PHP_EXTENSION_XDEBUG: "true"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - SLIM_4_API